### ISSUE TITLE
App not working in android 7.0

### ISSUE THREAD

**Issue by iamjaspreetsingh** [rtgdk/VizAid#1]
After installing the app from given apk, and giving all permissions, app doesn't work
Just a splash screen is coming with audio and nothing is happening as such by swiping down. On swiping right or left app is closing
Is it that your microsoft subscription to api is expired?
Please check 

Also, the direct link to get permissions for above 6.0 version (after checking) can be given 
I would surely like to work on it. 

Thank you

**Comment by rtgdk** [comment]
Hey Jaspreet,
Thanks for reporting. This project was created as part of our Code Fun Do project. We used free api subscription that Microsoft gives while the competition was up. It expired 2 months after that. If you want to test the project you can get a trial api key from https://azure.microsoft.com/en-in/try/cognitive-services/ . 
Also, regarding the permission issue. I would be very glad if you can fix it up. 
(This app was made in one night, figuring out the bug took us a lot of time. We were also newbie while we created this app. So had to introduce that readme instruction for giving access without solving the bug.)

**Comment by iamjaspreetsingh** [comment]
Added the permission #2
